#!/bin/bash

set -e
set -o pipefail

if test -n "$AWS_ROLE"; then
    echo "Assuming IAM role $AWS_ROLE ..."
    aws sts assume-role --role-arn "$AWS_ROLE" --role-session-name serverless | \
        jq -r '.Credentials | {AWS_ACCESS_KEY_ID: .AccessKeyId, AWS_SECRET_ACCESS_KEY: .SecretAccessKey, AWS_SESSION_TOKEN: .SessionToken} | to_entries | .[] | .key + "=" + .value' \
        > /aws.env
    source /aws.env
    export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
fi

exec "$@"
